### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by peeld** [obsproject/obs-websocket#1024]
### Feature Request Type

RPC Request

### Feature Request Type (Other)

SetFilenameFormatting Request.

### Requested Feature

It would be great to have the ability to remotely name the file that is about to be recorded.

I searched the tickets and found a reference to finding the current file name and renaming it after it is created, but that requires the process to be running on the same pc, when the record-start command event is coming from a different PC then it is not as easy to rename the file.

Previously this was implemented by "SetFilenameFormatting" request.

When users upgrade their OBS to the latest version it the latest version of obs websocket and this introduces a breaking change for me as this feature is not available.

Thanks!

### Requested Feature Usage Scenario

OBS is being triggered from a different computer and the recording file name and record start/top needs to be set by the remote computer.  The remote computer does not have access to the filesystem that OBS is writing to.

**Comment by jeiea** [comment]
Actually it is still possible, just it is complicated.

With `SetProfileParameter` RPC you can set OBS settings. Your filename setting is `Output.FilenameFormatting`. Because `SetProfileParameter` may not be applied immediately, it is safe to change to another profile and return back.

After that it will be similar to invoke `SetFilenameFormatting`. My two cents, and I didn't verified it.

**Comment by peeld** [comment]
Thanks for the tip @jeiea - I was able to get it to work by sending this:
command = 'SetProfileParameter'
argument = {'parameterCategory': 'Output', 'parameterName': 'FilenameFormatting', 'parameterValue': argument }
