### ISSUE TITLE
websocket fail to load (any 4.9.0 and above)

### ISSUE THREAD

**Issue by SirHater** [obsproject/obs-websocket#1051]
### Operating System Info

Windows 11

### OBS Studio Version

Other

### OBS Studio Version (Other)

28.1.2

### obs-websocket Version

5.0.1

### OBS Studio Log URL

https://obsproject.com/logs/p9uM89IP1aKaJTMb

### OBS Studio Crash Log URL

None

### Expected Behavior

Install websocket and try use Mix It Up but i got a problem on Websocket.

### Current Behavior

I installed 5.0.1 version and OBS say:

---------------------------
Plugin Load Error
---------------------------
The following OBS plugins failed to load:

obs-websocket

Please update or remove these plugins.

I tried others versions and the same think happen. 

I'm using StreamElements OBS (this error never happened to me before i installed windows 11) and the version: SE.Live Core ver. 22.9.869

### Steps to Reproduce

I only installed the websocket and this error is ocurring.

### Anything else we should know?

THis never happen before i install windows 11, maybe its a problem with the OS?

**Comment by TheHyperSloth** [comment]
I also have this issue.
Windows 10.
OBS 28.1.2
Websocket 5.0.1 / 4.9.1(compat)

Neither works, and OBS throws:
The following OBS plugins failed to load:

obs-websocket-compat
obs-websocket

Please update or remove these plugins.

The plugin IS working on 28.1

I re-installed OBS 28.1 and Websocket 5.0.1 loads, however 4.9.1(compat) does not.
I hope this helps narrow down which OBS version caused this hiccup.

**Comment by tt2468** [comment]
This issue is happening because you are installing a version of obs-websocket that is built for OBS 27. It actually says in the release notes to only use it with OBS 27. OBS 28 comes with obs-websocket 5.x installed by default, so installing the 27 version just overwrites the correct binary with one that doesn't work properly.

Use the `Help -> Check for integrity` button in OBS to fix obs-websocket, and download the obs-websocket-compat release that is labeled as being for OBS 28: https://github.com/obsproject/obs-websocket/releases/tag/4.9.1-compat
