### ISSUE TITLE
Bug: websocket per profile not working

### ISSUE THREAD

**Issue by veravsms** [obsproject/obs-websocket#1127]
### Operating System Info

Windows 11

### OBS Studio Version

28.1.x

### obs-websocket Version

5.1.0

### OBS Studio Log URL

https://obsproject.com/logs/uVUFYUaogKom2bqa

### Expected Behavior

Each profile saves its own WebSocket settings.

### Current Behavior

WebSocket is saved globally instead of the profile as stated here. https://github.com/obsproject/obs-websocket/issues/269

### Steps to Reproduce

1.profile 1, websocket = 1
2.profile 2, websocket = 2
3.use profile 1 and change websocket to 1000
4.restart obs
result:
profile 1, websocket =1000
profile 2, websocket =1000
expected behavior:
profile 1, websocket =1000
profile 2, websocket =2

### Anything else we should know?

https://github.com/obsproject/obs-websocket/issues/269

**Comment by tt2468** [comment]
This is not a bug, it's by design. To mimic behavior of per-profile obs-websocket settings, please use [the available startup command line parameters](https://github.com/obsproject/obs-websocket#:~:text=(Psst.%20You%20can%20use%20%2D%2Dwebsocket_port(value)%2C%20%2D%2Dwebsocket_password(value)%2C%20%2D%2Dwebsocket_debug(flag)%20and%20%2D%2Dwebsocket_ipv4_only(flag)%20on%20the%20command%20line%20to%20override%20the%20configured%20values.)). On Windows, I recommend creating shortcuts which specify parameters to override the WebSocket port and the profile/scene collection.
