### ISSUE TITLE
How to Set record directory folder 

### ISSUE THREAD

**Issue by LuchunPen** [obsproject/obs-websocket#1142]
### Feature Request Type

RPC Request

### Requested Feature

Hello !
I want to create some cuts of video and set it in different directories.
Ho could I set record directory by API ? There is only GerRecordDirectory(). 

Thanks

### Requested Feature Usage Scenario

No

**Comment by dhruv-prajapati** [comment]
When we can expect his feature to go live.

**Comment by SpaceBod** [comment]
@dhruv-prajapati, in case you still need a solution:

Since OBS Studio currently doesn't have v5.3.0 implemented, you can't use **SetRecordDirectory**, you can use the old method's **SetProfileParameter**:

This is for JavaScript

```
// Sets a new recording path
obs.call('SetProfileParameter', { 'parameterCategory': 'SimpleOutput', 'parameterName': 'FilePath', 'parameterValue': selectedFolderPath })

// Prints the now changed values
obs.call('GetProfileParameter', { 'parameterCategory': 'SimpleOutput', 'parameterName': 'FilePath' })
    .then(result => {
        console.log('Result:', result);
    })
    .catch(error => {
        console.error('Error:', error);
    });
```

What worked for me was setting:
parameterCategory -> "SimpleOutput"
parameterName -> "FilePath"

**Comment by LuchunPen** [comment]
Amazing! I really glad to see that, thanks :)
