### ISSUE TITLE
Feature Request: Access to IP Binding settings

### ISSUE THREAD

**Issue by lizaoreo** [obsproject/obs-websocket#931]
### Feature Request Type

RPC Request

### Requested Feature

The ability to specifically get the status of whether OBS is set to bind to IP and if so, what IP.  It may also be helpful to be able to get a list of options available and set one, but just being able to see what is set would be helpful.

### Requested Feature Usage Scenario

I currently have to use my cell phone tethered for streaming.  This means I have to bind OBS to whatever IP my cell phone gives the computer.  This IP changes whenever I have to restart my phone for updates or any other reason.  Being able to pull the bind status and verify that it is currently connected to my phone, and not the regular network, would allow me to automate starting my normal streams at the normal times automatically based on the condition my phone was present.

In theory being able to pull all available sources and set the stream IP would allow me to automatically update OBS as well in the case my phone's provided IP changes.

**Comment by malliaridis** [comment]
Does this relate to https://github.com/obsproject/obs-websocket/issues/928?

**Comment by tt2468** [comment]
obs-websocket binds to `::/0` (ipv6 version of 0.0.0.0/0), so there is little benefit to allowing specific selection of bind interface. The Connect Info dialog is simply a best guess among your interfaces of what network you might actually be intending to connect from. It does not correlate to where obs-websocket is accessible from, since obs-websocket makes itself accessible to everything possible.
